# -*- coding: utf-8 -*-
with open("make_full_car_docx.py", "r", encoding="utf-8") as f:
    content = f.read()

content = content.replace("line_spacing=320", "line_spacing=276")
content = content.replace('align="both"', 'align="left"')
content = content.replace("first_line=720", "first_line=567")
content = content.replace("left_indent=720, hanging=360", "left_indent=640, hanging=320")
content = content.replace("space_before=60, space_after=60, line_spacing=276", "space_before=0, space_after=0, line_spacing=276")
content = content.replace("space_before=40, space_after=40, line_spacing=276", "space_before=0, space_after=0, line_spacing=276")
content = content.replace("space_before=40, space_after=60, line_spacing=276", "space_before=0, space_after=0, line_spacing=276")
content = content.replace("space_before=30, space_after=30, line_spacing=276", "space_before=0, space_after=0, line_spacing=276")
content = content.replace("space_before=160, space_after=80, keep_next=True", "space_before=200, space_after=60, keep_next=True")
content = content.replace("space_before=140, space_after=80, keep_next=True", "space_before=200, space_after=60, keep_next=True")
content = content.replace("space_before=60, space_after=60, keep_next=True", "space_before=120, space_after=40, keep_next=True")
content = content.replace("space_before=80, space_after=60, keep_next=True", "space_before=120, space_after=40, keep_next=True")
content = content.replace("line_spacing=300", "line_spacing=276")
content = content.replace("space_before=40, space_after=400, line_spacing=276", "space_before=40, space_after=240, line_spacing=296")
content = content.replace("space_before=0, space_after=500, line_spacing=276", "space_before=40, space_after=200, line_spacing=260")
content = content.replace("space_before=80, space_after=600, line_spacing=276", "space_before=60, space_after=240, line_spacing=260")
content = content.replace("space_before=600, space_after=200", "space_before=480, space_after=160")
content = content.replace("space_before=40, space_after=40, line_spacing=276", "space_before=0, space_after=0, line_spacing=276")
content = content.replace("space_before=20, space_after=20, line_spacing=276", "space_before=0, space_after=0, line_spacing=276")
content = content.replace("space_before=20, space_after=120, line_spacing=276", "space_before=0, space_after=80, line_spacing=276")
content = content.replace("space_before=60, space_after=120, line_spacing=276", "space_before=0, space_after=80, line_spacing=276")
content = content.replace("space_before=40, space_after=140, line_spacing=276", "space_before=0, space_after=80, line_spacing=276")
content = content.replace("space_before=40, space_after=100", "space_before=20, space_after=60")
content = content.replace("space_before=40, space_after=80", "space_before=0, space_after=60")
content = content.replace("space_before=80, space_after=100", "space_before=0, space_after=0")
content = content.replace("space_before=60, space_after=80", "space_before=0, space_after=0")
content = content.replace("space_before=80, space_after=80", "space_before=0, space_after=0")
content = content.replace("space_before=40, space_after=80", "space_before=0, space_after=0")

n_left = content.count('align="left"')
n_both = content.count('align="both"')
n_276 = content.count("line_spacing=276")
n_320 = content.count("line_spacing=320")
n_567 = content.count("first_line=567")
n_720 = content.count("first_line=720")

print("== Fix Summary ==")
print("  align=left:", n_left)
print("  align=both remaining:", n_both)
print("  line_spacing=276:", n_276)
print("  line_spacing=320 remaining:", n_320)
print("  first_line=567:", n_567)
print("  first_line=720 remaining:", n_720)

with open("make_full_car_docx.py", "w", encoding="utf-8") as f:
    f.write(content)

print("Done.")
